### PR TITLE
docs: Add usage to README

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 4db2e8b has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 4db2e8b with merge 91f1510...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/git2-commit-rs/builds/123853519)

**Pull request merged**
