### PR TITLE
chore: Enable homu webhook

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit a1b2cd0 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit a1b2cd0 with merge c0ac348...

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by ghost** [comment]
:hourglass: Testing commit a1b2cd0 with merge 5b02281...

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by ghost** [comment]
:hourglass: Testing commit a1b2cd0 with merge a73e801...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/badboy/git2-commit-rs/builds/123387836)

**Pull request merged**
