### PR TITLE
chore: Remove travis webhook

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit d99bcfc has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit d99bcfc with merge 4a9ded8...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/git2-commit-rs/builds/123545901)

**Pull request merged**
